rooms:
  salle_101:
    x: -8.1
    y: -6.62
    orientation_w: 0.5199
    aliases: ["room 101", "salle 101", "chambre 101"]
  salle_102:
    x: -8.90481734101325
    y: -15.881
    orientation_w: 0.5199
    aliases: ["room 102", "salle 102", "chambre 102"]
  salle_202:
    x: 8.912
    y: -20.42
    orientation_w: 0.5199
    aliases: ["room 202", "salle 202", "chambre 202"]
  salle_201:
    x: 7.91
    y: -6.77
    orientation_w: 0.5199
    aliases: ["room 201", "salle 201", "chambre 201"]
  salle_cuisine:
    x: -8.66
    y: -27.77
    orientation_w: 0.5199
    aliases: ["cuisine", "salle cuisine", "kitchen"]
  salle_reception:
    x: 2.55
    y: 7.49
    orientation_w: 0.5199
    aliases: ["reception", "salle reception", "reception"]
  charging_station:
    x: 0.0
    y: 1.95
    orientation_w: 1.0
    aliases: ["charging station", "station de charge", "charge station"]
  salle_pharmacie:
    x: -7.96
    y: 14.61
    orientation_w: 0.5199
    aliases: ["pharmacie", "salle pharmacie", "pharmacy"]